import fs from "fs";
import path from "path";

export function generateConfigs(repoDir: string | null, detected: Record<string, any>) {
  const generatedFiles: Record<string, string> = {};

  // ✅ Safe file writer with debugging. If repoDir is null we only keep files in-memory.
  const writeFile = (filename: string, content: any) => {
    try {
      if (typeof content !== "string") {
        console.error(`⚠️ Invalid content for ${filename}:`, content);
        throw new Error(`Invalid content type for ${filename}`);
      }

      generatedFiles[filename] = content;

      if (repoDir) {
        const filePath = path.join(repoDir, filename);
        fs.writeFileSync(filePath, content.trim() + "\n");
      }
    } catch (err) {
      console.error(`❌ Error writing ${filename}:`, err);
      generatedFiles[filename] = `Error: ${(err as Error).message}`;
    }
  };

  // 1️⃣ Dockerfile (Express, Flask, FastAPI)
  if (detected.backend === "Express.js" || detected.backend === "Flask" || detected.backend === "FastAPI") {
    writeFile(
      "Dockerfile",
      `
# Auto-generated by DeployMate
FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
CMD ["npm", "start"]
`
    );
  }

  // 2️⃣ Vercel config for Next.js
  if (detected.frontend === "Next.js") {
    writeFile(
      "vercel.json",
      `
{
  "version": 2,
  "builds": [{ "src": "package.json", "use": "@vercel/next" }],
  "routes": [{ "src": "/(.*)", "dest": "/$1" }]
}
`
    );
  }

  // 3️⃣ Netlify config (React or Vue)
  if (detected.frontend === "React" || detected.frontend === "Vue") {
    writeFile(
      "netlify.toml",
      `
[build]
  command = "npm run build"
  publish = "build"
`
    );
  }

  // 4️⃣ README summary — always generated
  writeFile(
    "DEPLOYMATE_SUMMARY.md",
    `
# 🚀 DeployMate Summary

**Detected Stack**
- Language: ${detected.language || "Unknown"}
- Frontend: ${detected.frontend || "None"}
- Backend: ${detected.backend || "None"}
- Database: ${detected.database || "None"}
- Deployment: ${detected.deployment || "None"}

Generated automatically by DeployMate ✨
`
  );

  return generatedFiles;
}
